#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

pushd ${OPENSHIFT_REPO_DIR} > /dev/null

if [ -z "$SECRET_TOKEN" ]
then
    export SECRET_TOKEN="$(RAILS_ENV=${RAILS_ENV:-production} bundle exec rake secret)"
fi

bundle exec rake errbit:copy_configs RAILS_ENV=${RAILS_ENV:-production}

echo "exec rake db:migrate RAILS_ENV=${RAILS_ENV:-production}"
bundle exec rake db:migrate RAILS_ENV=${RAILS_ENV:-production}
popd > /dev/null
