plugins:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-erb
  - rubocop-disable_syntax

inherit_mode:
  merge:
    - Exclude

inherit_gem:
  standard: config/ruby-3.4.yml

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  Exclude:
    - "bin/*"
