plugins:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

# Enforced by standard. Disable.
Style/StringLiterals:
  Enabled: false

# Enforced by standard. Disable.
Layout/HashAlignment:
  Enabled: false

# Enforced by standard. Disable.
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# Enforced by standard. Disable.
Layout/SpaceInsideStringInterpolation:
  Enabled: false

# Enforced by standard. Disable.
Style/HashSyntax:
  Enabled: false

# Enforced by standard. Disable.
Style/NestedParenthesizedCalls:
  Enabled: false

# Enforced by standard. Disable.
Layout/DotPosition:
  Enabled: false

# Enforced by standard. Disable.
Layout/ExtraSpacing:
  Enabled: false

# Enforced by standard. Disable.
Layout/ArgumentAlignment:
  Enabled: false

# Enforced by standard. Disable.
Lint/ImplicitStringConcatenation:
  Enabled: false

# Enforced by standard. Disable.
Lint/TripleQuotes:
  Enabled: false

# Enforced by rubocop and standard
Security/JSONLoad:
  Enabled: true
