---
inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true

# Caveat: .find_by raises exception in mongoid, unlike ActiveRecord which
# returns nil
Rails/FindBy:
  Enabled: false

Lint/DefEndAlignment:
  AlignWith: start_of_line

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/IndentationConsistency:
  # `rails` style:
  # prescribes that in classes and modules the `protected` and `private`
  # modifier keywords shall be indented the same as public methods and that
  # protected and private members shall be indented one step more than the
  # modifiers.
   EnforcedStyle: rails

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
