plugins:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

# Enforced by standard. Disable.
Style/StringLiterals:
  Enabled: false

# Enforced by standard. Disable.
Layout/HashAlignment:
  Enabled: false

# Enforced by standard. Disable.
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# Enforced by standard. Disable.
Layout/SpaceInsideStringInterpolation:
  Enabled: false

# Enforced by standard. Disable.
Style/HashSyntax:
  Enabled: false

# Enforced by standard. Disable.
Style/NestedParenthesizedCalls:
  Enabled: false

# Enforced by standard. Disable.
Layout/DotPosition:
  Enabled: false

# Enforced by standard. Disable.
Layout/ExtraSpacing:
  Enabled: false

# Enforced by standard. Disable.
Layout/ArgumentAlignment:
  Enabled: false

# Enforced by standard. Disable.
Lint/ImplicitStringConcatenation:
  Enabled: false

# Enforced by standard. Disable.
Lint/TripleQuotes:
  Enabled: false

# Enforced by rubocop and standard
Security/JSONLoad:
  Enabled: true

# Enforced by standard. Disable.
Style/RedundantRegexpArgument:
  Enabled: false

# Enforced by standard. Disable.
Style/PercentLiteralDelimiters:
  Enabled: false

# Enforced by standard. Disable.
Layout/MultilineMethodCallBraceLayout:
  Enabled: false

# Enforced by standard. Disable.
Style/Encoding:
  Enabled: false

# Enforced by standard. Disable.
Style/NumericLiteralPrefix:
  Enabled: false

# Enforced by standard. Disable.
Layout/AccessModifierIndentation:
  Enabled: false

# Enforced by standard. Disable.
Style/RedundantParentheses:
  Enabled: false

# Enforced by standard. Disable.
Lint/IneffectiveAccessModifier:
  Enabled: false

# Enforced by standard. Disable.
Layout/FirstHashElementIndentation:
  Enabled: false

# Enforced by standard. Disable.
Lint/SymbolConversion:
  Enabled: false

# Enforced by standard. Disable.
Style/RedundantBegin:
  Enabled: false

# Enforced by standard. Disable.
Style/SuperWithArgsParentheses:
  Enabled: false

# Enforced by standard. Disable.
Layout/IndentationWidth:
  Enabled: false

# Enforced by standard. Disable.
Style/SafeNavigation:
  Enabled: false

# Enforced by standard. Disable.
Layout/ElseAlignment:
  Enabled: false

# Enforced by rubocop and standard
Lint/CopDirectiveSyntax:
  Enabled: true

# Enforced by standard. Disable.
Style/EmptyMethod:
  Enabled: false

# Enforced by standard. Disable.
Style/SingleLineMethods:
  Enabled: false

# Enforced by standard. Disable.
Layout/EndAlignment:
  Enabled: false

# Enforced by standard. Disable.
Style/RescueStandardError:
  Enabled: false

# Enforced by standard-performance. Disable.
Performance/Detect:
  Enabled: false

# Enforced by standard-performance. Disable.
Performance/StringIdentifierArgument:
  Enabled: false

# Enforced by standard. Disable.
Lint/DuplicateMethods:
  Enabled: false

# Enforced by standard. Disable.
Style/RedundantSelf:
  Enabled: false

# Enforced by standard. Disable.
Style/TernaryParentheses:
  Enabled: false

# Enforced by standard. Disable.
Lint/ConstantDefinitionInBlock:
  Enabled: false

# Enforced by standard. Disable.
Layout/MultilineHashBraceLayout:
  Enabled: false

# Enforced by standard. Disable.
Layout/EmptyLineBetweenDefs:
  Enabled: false

# Enforced by standard. Disable.
Lint/UselessTimes:
  Enabled: false

# Enforced by standard. Disable.
Layout/MultilineArrayBraceLayout:
  Enabled: false

# Enforced by standard. Disable.
Style/ConditionalAssignment:
  Enabled: false

# Enforced by standard. Disable.
Layout/EmptyLineAfterMagicComment:
  Enabled: false

# Enforced by standard. Disable.
Layout/SpaceAroundOperators:
  Enabled: false

# Enforced by standard. Disable.
Layout/ArrayAlignment:
  Enabled: false

# Enforced by standard. Disable.
Layout/AssignmentIndentation:
  Enabled: false

# Enforced by standard. Disable.
Style/ItAssignment:
  Enabled: false

# Enforced by standard. Disable.
Style/EachWithObject:
  Enabled: false

# Enforced by standard. Disable.
Layout/ClosingParenthesisIndentation:
  Enabled: false

# Enforced by standard. Disable.
Style/RedundantLineContinuation:
  Enabled: false

# Enforced by standard. Disable.
Style/SlicingWithRange:
  Enabled: false

# Enforced by standard. Disable.
Style/MultilineIfModifier:
  Enabled: false

# Enforced by standard. Disable.
Style/RedundantCondition:
  Enabled: false

# Enforced by standard. Disable.
Style/RedundantInterpolation:
  Enabled: false

# Enforced by standard. Disable.
Style/OrAssignment:
  Enabled: false

# Enforced by standard-performance. Disable.
Performance/RegexpMatch:
  Enabled: false

# Enforced by standard. Disable.
Style/GlobalStdStream:
  Enabled: false
