# frozen_string_literal: true

require "rails_helper"
require "airbrake"

RSpec.describe ErrorReport, type: :model do
  let(:notice_attrs) do
    {
      error_class: "TestError",
      message: "TestError: Something broke",
      backtrace: [
        {"number" => "12", "file" => "[PROJECT_ROOT]/app/models/user.rb", "method" => "find"},
        {"number" => "34", "file" => "[GEM_ROOT]/gems/mongoid/lib/mongoid.rb", "method" => "load"}
      ],
      request: {
        "url" => "http://example.org/users/1",
        "params" => {"controller" => "users", "action" => "show"},
        "cgi-data" => {"HTTP_USER_AGENT" => "RSpec", "SERVER_NAME" => "example.org"},
        "component" => "users",
        "action" => "show"
      },
      server_environment: {
        "environment-name" => "development",
        "app-version" => "1.0",
        "hostname" => "example.org"
      },
      api_key: "APIKEY",
      notifier: {"name" => "Test Notifier", "version" => "1.0", "url" => "https://example.org/notifier"},
      user_attributes: {
        "id" => "123",
        "name" => "Mr. Bean",
        "email" => "mr.bean@example.com",
        "username" => "mrbean"
      },
      framework: "Rails: 8.0.2"
    }
  end

  let(:error_report) { ErrorReport.new(notice_attrs) }

  let!(:app) { create(:app, api_key: "APIKEY") }

  describe "#app" do
    it "find the good app" do
      expect(error_report.app).to eq(app)
    end
  end

  describe "#backtrace" do
    it "should have valid backtrace" do
      expect(error_report.backtrace.valid?).to eq(true)
    end
  end

  describe "#generate_notice!" do
    it "save a notice" do
      expect do
        error_report.generate_notice!
      end.to change(app.reload.problems, :count).by(1)
    end

    context "with notice generated by Airbrake gem" do
      after { Airbrake.reset }

      let(:exception) do
        StandardError.new("TestError").tap do |error|
          error.set_backtrace(["#{Rails.root}/app/models/user.rb:12:in `find'"])
        end
      end

      let(:airbrake_notice) do
        JSON.parse(Airbrake.build_notice(exception).to_json)
      end

      let(:params) do
        airbrake_notice.merge("key" => app.api_key)
      end

      let(:error_report) { AirbrakeApi::V3::NoticeParser.new(params).report }

      it "saves a notice" do
        expect do
          error_report.generate_notice!
        end.to change(app.reload.problems, :count).by(1)
      end
    end

    describe "notice create" do
      before { error_report.generate_notice! }

      subject { error_report.notice }

      it "has correct message" do
        expect(subject.message).to eq("TestError: Something broke")
      end

      it "has correct framework" do
        expect(subject.framework).to eq("Rails: 8.0.2")
      end

      it "has complete backtrace" do
        expect(subject.backtrace_lines.size).to eq(2)

        expect(subject.backtrace_lines.last["file"]).to eq("[GEM_ROOT]/gems/mongoid/lib/mongoid.rb")
      end

      it "has server_environment" do
        expect(subject.server_environment["environment-name"]).to eq("development")
      end

      it "has request" do
        expect(subject.request["url"]).to eq("http://example.org/users/1")

        expect(subject.request["params"]["controller"]).to eq("users")
      end

      it "has notifier" do
        expect(subject.notifier["name"]).to eq("Test Notifier")
      end

      it "get user_attributes" do
        expect(subject.user_attributes["id"]).to eq("123")

        expect(subject.user_attributes["name"]).to eq("Mr. Bean")

        expect(subject.user_attributes["email"]).to eq("mr.bean@example.com")

        expect(subject.user_attributes["username"]).to eq("mrbean")
      end

      it "has env_vars" do
        expect(subject.env_vars).to include("HTTP_USER_AGENT" => "RSpec")
      end
    end
  end

  describe "#cache_attributes_on_problem" do
    it "sets the latest notice properties on the problem" do
      error_report.generate_notice!
      problem = error_report.problem.reload
      notice = error_report.notice.reload

      expect(problem.environment).to eq("development")

      expect(problem.error_class).to eq("TestError")

      expect(problem.last_notice_at).to eq(notice.created_at)

      expect(problem.message).to eq(notice.message)

      expect(problem.where).to eq(notice.where)
    end

    it "unresolves the problem" do
      error_report.generate_notice!
      problem = error_report.problem
      problem.update!(
        resolved_at: Time.zone.now,
        resolved: true
      )

      error_report = ErrorReport.new(notice_attrs)
      error_report.generate_notice!
      problem.reload

      expect(problem.resolved_at).to eq(nil)

      expect(problem.resolved).to eq(false)
    end

    it "caches notice counts" do
      error_report.generate_notice!
      problem = error_report.problem
      problem.reload

      expect(problem.notices_count).to eq(1)

      expect(problem.user_agents.values.first["count"]).to eq(1)

      expect(problem.messages.values.first["count"]).to eq(1)

      expect(problem.hosts.values.first["count"]).to eq(1)
    end

    it "increments notice counts" do
      error_report.generate_notice!
      error_report = ErrorReport.new(notice_attrs)
      error_report.generate_notice!
      problem = error_report.problem
      problem.reload

      expect(problem.notices_count).to eq(2)

      expect(problem.user_agents.values.first["count"]).to eq(2)

      expect(problem.messages.values.first["count"]).to eq(2)

      expect(problem.hosts.values.first["count"]).to eq(2)
    end
  end

  it "save a notice assignes to err" do
    error_report.generate_notice!
    expect(error_report.notice.err).to be_a(Err)
  end

  it "memoize the notice" do
    expect do
      error_report.generate_notice!

      error_report.generate_notice!
    end.to change(Notice, :count).by(1)
  end

  it "find the correct err for the notice" do
    error_report.generate_notice!
    error_report.problem.resolve!

    expect do
      ErrorReport.new(notice_attrs).generate_notice!
    end.to change {
      error_report.problem.reload.resolved?
    }.from(true).to(false)
  end

  context "with notification service configured" do
    before do
      app.notify_on_errs = true
      app.save
      app.watchers.build(email: "foo@example.com")
      app.save
    end

    it "send email" do
      notice = error_report.generate_notice!
      email = ActionMailer::Base.deliveries.last
      expect(email.to).to include(app.watchers.first.email)
      expect(email.subject).to include(notice.message.truncate(50))
      expect(email.subject).to include("[#{app.name}]")
      expect(email.subject).to include("[#{notice.environment_name}]")
    end

    context "when email_at_notices config is specified", type: :mailer do
      before do
        allow(Errbit::Config).to receive(:email_at_notices).and_return(email_at_notices)
      end

      context "as [0]" do
        let(:email_at_notices) { [0] }

        it "sends email on 1st occurrence" do
          described_class.new(notice_attrs).generate_notice!

          expect(ActionMailer::Base.deliveries.length).to eq(1)
        end

        it "sends email on 2nd occurrence" do
          2.times { described_class.new(notice_attrs).generate_notice! }

          expect(ActionMailer::Base.deliveries.length).to eq(2)
        end

        it "sends email on 3rd occurrence" do
          3.times { described_class.new(notice_attrs).generate_notice! }

          expect(ActionMailer::Base.deliveries.length).to eq(3)
        end
      end

      context "as [1,3]" do
        let(:email_at_notices) { [1, 3] }

        it "sends email on 1st occurrence" do
          described_class.new(notice_attrs).generate_notice!

          expect(ActionMailer::Base.deliveries.length).to eq(1)
        end

        it "does not send email on 2nd occurrence" do
          2.times { described_class.new(notice_attrs).generate_notice! }

          expect(ActionMailer::Base.deliveries.length).to eq(1)
        end

        it "sends email on 3rd occurrence" do
          3.times { described_class.new(notice_attrs).generate_notice! }

          expect(ActionMailer::Base.deliveries.length).to eq(2)
        end

        it "sends email on all occurrences when problem was resolved" do
          3.times do
            notice = described_class.new(notice_attrs).generate_notice!
            notice.problem.resolve!
          end

          expect(ActionMailer::Base.deliveries.length).to eq(3)
        end
      end
    end

  end

  describe "#valid?" do
    context "with valid error report" do
      it "return true" do
        expect(error_report.valid?).to eq(true)
      end
    end

    context "with not valid api_key" do
      before do
        App.where(api_key: app.api_key).delete_all
      end

      it "return false" do
        expect(error_report.valid?).to eq(false)
      end
    end
  end

  describe "#notice" do
    context "before generate_notice!" do
      it "return nil" do
        expect(error_report.notice).to eq(nil)
      end
    end

    context "after generate_notice!" do
      before do
        error_report.generate_notice!
      end

      it "return the notice" do
        expect(error_report.notice).to be_a(Notice)
      end
    end
  end

  describe "#should_keep?" do
    context "with current app version not set" do
      before do
        error_report.app.current_app_version = nil

        error_report.server_environment["app-version"] = "1.0"
      end

      it "return true" do
        expect(error_report.should_keep?).to eq(true)
      end
    end

    context "with current app version set" do
      before do
        error_report.app.current_app_version = "1.0"
      end

      it "return true if current or newer" do
        error_report.server_environment["app-version"] = "1.0"

        expect(error_report.should_keep?).to eq(true)
      end

      it "return false if older" do
        error_report.server_environment["app-version"] = "0.9"

        expect(error_report.should_keep?).to eq(false)
      end
    end
  end
end
