# Mongoid Configuration for MongoLab on Heroku
# ===========================================
#
# Copy this file to config/mongoid.yml,
# commit it to your repo, then push to heroku.

production:
  uri: <%= ENV['MONGOLAB_URI'] %>
  identity_map_enabled: true
