apiVersion: v1
kind: Service
metadata:
  name: errbit
  namespace: default
  labels:
    name: errbit
spec:
  ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
  selector:
    name: errbit
