# frozen_string_literal: true

require "rails_helper"

require "airbrake/version"
require "airbrake/backtrace"
require "airbrake/notice"
require "airbrake/utils/params_cleaner"

# Allow building an Airbrake::Notice without configuring Airbrake first.
module Airbrake
  API_VERSION = "2.4"

  class Notice
    def framework
      "rails"
    end
  end
end

RSpec.describe Errbit::ErrorReport, type: :model do
  let(:xml) { Rails.root.join("spec/fixtures/hoptoad_test_notice.xml").read }
  let(:error_report) { described_class.new(xml) }
  let!(:app) { create(:errbit_app, api_key: "APIKEY") }
  let!(:notice_fingerprinter) { create(:errbit_notice_fingerprinter, app: app) }

  describe "#app" do
    it "finds the app by api_key" do
      expect(error_report.app).to eq(app)
    end
  end

  describe "#backtrace" do
    it "returns a persisted Errbit::Backtrace" do
      bt = error_report.backtrace

      expect(bt).to be_a(Errbit::Backtrace)
      expect(bt).to be_persisted
    end
  end

  describe "#generate_notice!" do
    it "creates a problem for the app" do
      expect { error_report.generate_notice! }
        .to change { app.reload.problems.count }.by(1)
    end

    context "with a minimal notice XML" do
      let(:xml) { Rails.root.join("spec/fixtures/minimal_test_notice.xml").read }

      it "creates a problem for the app" do
        expect { error_report.generate_notice! }
          .to change { app.reload.problems.count }.by(1)
      end
    end

    context "with a notice generated by the Airbrake gem" do
      let(:xml) do
        Airbrake::Notice.new(
          exception: Exception.new,
          api_key: "APIKEY",
          project_root: Rails.root
        ).to_xml
      end

      it "creates a problem for the app" do
        expect { error_report.generate_notice! }
          .to change { app.reload.problems.count }.by(1)
      end
    end

    context "after generating the notice" do
      subject(:notice) { error_report.notice }

      before { error_report.generate_notice! }

      it "stores the error message" do
        expect(notice.message).to include('HoptoadTestingException: Testing hoptoad via "rake hoptoad:test". If you can see this, it works')
      end

      it "stores the framework" do
        expect(notice.framework).to eq("Rails: 3.2.11")
      end

      it "stores the full backtrace" do
        expect(notice.backtrace_lines.size).to eq(73)
        expect(notice.backtrace_lines.last["file"]).to eq("[GEM_ROOT]/bin/rake")
      end

      it "stores server_environment" do
        expect(notice.server_environment["environment-name"]).to eq("development")
      end

      it "stores the request hash" do
        expect(notice.request["url"]).to eq("http://example.org/verify/cupcake=fistfight&lovebird=doomsayer")
        expect(notice.request["params"]["controller"]).to eq("application")
      end

      it "stores the notifier name" do
        expect(notice.notifier["name"]).to eq("Hoptoad Notifier")
      end

      it "stores user_attributes" do
        expect(notice.user_attributes["id"]).to eq("123")
        expect(notice.user_attributes["name"]).to eq("Mr. Bean")
        expect(notice.user_attributes["email"]).to eq("mr.bean@example.com")
        expect(notice.user_attributes["username"]).to eq("mrbean")
      end

      it "exposes parsed env_vars" do
        expect(notice.env_vars).to have_key("SCRIPT_NAME")
        expect(notice.env_vars["SCRIPT_NAME"]).to be_nil

        expected = {
          "secure" => "false",
          "httponly" => "true",
          "path" => "/",
          "expire_after" => nil,
          "domain" => nil,
          "id" => nil
        }
        expect(notice.env_vars).to have_key("rack_session_options")
        expect(notice.env_vars["rack_session_options"]).to eq(expected)
      end
    end
  end

  describe "#cache_attributes_on_problem" do
    it "writes the latest notice attributes onto the problem" do
      error_report.generate_notice!

      problem = error_report.problem.reload
      notice = error_report.notice.reload

      expect(problem.environment).to eq("development")
      expect(problem.error_class).to eq("HoptoadTestingException")
      expect(problem.last_notice_at.to_i).to eq(notice.created_at.to_i)
      expect(problem.message).to eq(notice.message)
      expect(problem.where).to eq(notice.where)
    end

    it "unresolves an already-resolved problem when a new notice arrives" do
      error_report.generate_notice!
      problem = error_report.problem
      problem.update!(resolved_at: Time.zone.now, resolved: true)

      described_class.new(xml).generate_notice!
      problem.reload

      expect(problem.resolved_at).to be_nil
      expect(problem.resolved).to eq(false)
    end

    it "initializes the messages/hosts/user_agents digest counters" do
      error_report.generate_notice!
      problem = error_report.problem.reload

      expect(problem.notices_count).to eq(1)
      expect(problem.user_agents.values.first["count"]).to eq(1)
      expect(problem.messages.values.first["count"]).to eq(1)
      expect(problem.hosts.values.first["count"]).to eq(1)
    end

    it "increments the digest counters on repeat notices" do
      error_report.generate_notice!
      described_class.new(xml).generate_notice!
      problem = error_report.problem.reload

      expect(problem.notices_count).to eq(2)
      expect(problem.user_agents.values.first["count"]).to eq(2)
      expect(problem.messages.values.first["count"]).to eq(2)
      expect(problem.hosts.values.first["count"]).to eq(2)
    end
  end

  it "assigns the notice to an Errbit::Err" do
    error_report.generate_notice!

    expect(error_report.notice.err).to be_a(Errbit::Err)
  end

  it "memoizes the notice across repeated generate_notice! calls on the same instance" do
    expect {
      error_report.generate_notice!
      error_report.generate_notice!
    }.to change(Errbit::Notice, :count).by(1)
  end

  it "reuses the existing err on subsequent notices" do
    error_report.generate_notice!
    error_report.problem.resolve!

    expect {
      described_class.new(xml).generate_notice!
    }.to change {
      error_report.problem.reload.resolved?
    }.from(true).to(false)
  end

  context "with a notification recipient configured" do
    before do
      app.update!(notify_on_errs: true)
      app.watchers.create!(email: "foo@example.com")
    end

    it "delivers an email" do
      notice = error_report.generate_notice!
      email = ActionMailer::Base.deliveries.last

      expect(email.to).to include(app.watchers.first.email)
      expect(email.subject).to include(notice.message.truncate(50))
      expect(email.subject).to include("[#{app.name}]")
      expect(email.subject).to include("[#{notice.environment_name}]")
    end

    context "with email_at_notices set to [0]", type: :mailer do
      before { allow(Errbit::Config).to receive(:email_at_notices).and_return([0]) }

      it "delivers on the 1st occurrence" do
        described_class.new(xml).generate_notice!

        expect(ActionMailer::Base.deliveries.length).to eq(1)
      end

      it "delivers on the 2nd occurrence" do
        2.times { described_class.new(xml).generate_notice! }

        expect(ActionMailer::Base.deliveries.length).to eq(2)
      end

      it "delivers on the 3rd occurrence" do
        3.times { described_class.new(xml).generate_notice! }

        expect(ActionMailer::Base.deliveries.length).to eq(3)
      end
    end

    context "with email_at_notices set to [1, 3]", type: :mailer do
      before { allow(Errbit::Config).to receive(:email_at_notices).and_return([1, 3]) }

      it "delivers on the 1st occurrence" do
        described_class.new(xml).generate_notice!

        expect(ActionMailer::Base.deliveries.length).to eq(1)
      end

      it "does not deliver on the 2nd occurrence" do
        2.times { described_class.new(xml).generate_notice! }

        expect(ActionMailer::Base.deliveries.length).to eq(1)
      end

      it "delivers on the 3rd occurrence" do
        3.times { described_class.new(xml).generate_notice! }

        expect(ActionMailer::Base.deliveries.length).to eq(2)
      end

      it "delivers on every occurrence after the problem is resolved between notices" do
        3.times do
          notice = described_class.new(xml).generate_notice!
          notice.problem.resolve!
        end

        expect(ActionMailer::Base.deliveries.length).to eq(3)
      end
    end

    context "with XML that has no request section" do
      let(:xml) { Rails.root.join("spec/fixtures/hoptoad_test_notice_without_request_section.xml").read }

      it "still creates a problem for the app" do
        expect { error_report.generate_notice! }
          .to change { app.reload.problems.count }.by(1)
      end
    end

    context "with XML that has a single backtrace line" do
      let(:xml) { Rails.root.join("spec/fixtures/hoptoad_test_notice_with_one_line_of_backtrace.xml").read }

      it "still creates a problem for the app" do
        expect { error_report.generate_notice! }
          .to change { app.reload.problems.count }.by(1)
      end
    end
  end

  describe "#valid?" do
    context "with a known api_key" do
      it "returns true" do
        expect(error_report.valid?).to eq(true)
      end
    end

    context "with an unknown api_key" do
      # destroy_all cascades the dependent: :destroy on notice_fingerprinter
      # etc.; delete_all would violate the FK from errbit_notice_fingerprinters.
      before { Errbit::App.where(api_key: app.api_key).destroy_all }

      it "returns false" do
        expect(error_report.valid?).to eq(false)
      end
    end
  end

  describe "#notice" do
    context "before generate_notice!" do
      it "is nil" do
        expect(error_report.notice).to be_nil
      end
    end

    context "after generate_notice!" do
      before { error_report.generate_notice! }

      it "returns the persisted Errbit::Notice" do
        expect(error_report.notice).to be_a(Errbit::Notice)
      end
    end
  end

  describe "#should_keep?" do
    context "without a current_app_version on the app" do
      before do
        error_report.app.current_app_version = nil
        error_report.server_environment["app-version"] = "1.0"
      end

      it "returns true" do
        expect(error_report.should_keep?).to eq(true)
      end
    end

    context "with a current_app_version on the app" do
      before { error_report.app.current_app_version = "1.0" }

      it "returns true when the notice version matches the current version" do
        error_report.server_environment["app-version"] = "1.0"

        expect(error_report.should_keep?).to eq(true)
      end

      it "returns false when the notice version is older" do
        error_report.server_environment["app-version"] = "0.9"

        expect(error_report.should_keep?).to eq(false)
      end
    end
  end
end
