name: Bundler audit

on:
  push:
    branches:
      - main
      - 0-10-stable
      - 0-11-stable
  pull_request:
    branches:
      - main
      - 0-10-stable
      - 0-11-stable
  workflow_dispatch: {}
  schedule:
    - cron: "0 21 * * 6"

permissions:
  contents: read

jobs:
  bundler-audit:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            hosted-compute-watchdog-prod-eus-01.githubapp.com:443
            hosted-compute-watchdog-prod-eus-02.githubapp.com:443
            hosted-compute-watchdog-prod-iad-01.githubapp.com:443
            hosted-compute-watchdog-prod-iad-02.githubapp.com:443
            index.rubygems.org:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            rubygems.org:443

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set up Ruby
        uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1.312.0
        with:
          rubygems: latest
          bundler: latest
          bundler-cache: true
      - run: bin/bundle-audit update
      - run: bin/bundle-audit
