name: Bundler audit

on:
  push:
    branches:
      - main
      - 0-10-stable
  pull_request:
    branches:
      - main
      - 0-10-stable
  workflow_dispatch: {}
  schedule:
    - cron: "0 21 * * 6"

permissions:
  contents: read

jobs:
  bundler-audit:
    runs-on: ubuntu-24.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo-and-containers: true
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          rubygems: "3.6.9"
          bundler: "2.6.9"
          bundler-cache: true
      - run: bin/bundle-audit update
      - run: bin/bundle-audit
