name: Bundler audit

on:
  push:
    branches:
      - main
      - 0-10-stable
  pull_request:
    branches:
      - main
      - 0-10-stable
  workflow_dispatch: {}
  schedule:
    - cron: "0 21 * * 6"

permissions:
  contents: read

jobs:
  bundler-audit:
    runs-on: ubuntu-24.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo-and-containers: true
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          rubygems: "3.6.9"
          bundler: "2.6.9"
          bundler-cache: true
      - run: bin/bundle-audit update
      - run: bin/bundle-audit
