name: Standard

on:
  push:
    branches:
      - main
      - 0-11-stable
  pull_request:
    branches:
      - main
      - 0-11-stable
  workflow_dispatch: {}
  schedule:
    - cron: "0 21 * * 6"

permissions:
  contents: read

jobs:
  standard:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            index.rubygems.org:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            rubygems.org:443

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # v1.324.0
        with:
          rubygems: "4.0.21"
          bundler: "4.0.21"
          bundler-cache: true

      - run: |
          bin/standardrb \
            app/controllers/users_controller.rb \
            app/controllers/unlink_githubs_controller.rb \
            app/controllers/unlink_googles_controller.rb \
            app/models/problem.rb \
            app/models/notice.rb \
            app/models/user.rb \
            app/helpers \
            spec
